version: "3.7"
services:
  my_service:
    container_name: my_service
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "2525:2525"
      - "5858:5858"
    links:
      - my_service_db
    environment:
      - dev=1
      - db_service_name=my_service_db
      - db_name=example
      - db_user=admin
      - db_password=admin
      - db_retry_time=3000
  my_service_db:
    container_name: my_service_db
    image: postgres:latest
    # image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432" #make sure you change to 5433 if you have postgres installed locally
volumes:
  pgdata: